### ISSUE TITLE
iTerm 2 theme?

### ISSUE THREAD

**Issue by tomspeak** [sonjapeterson/1989.vim#7]
Yowzers, nice theme.

Was wondering if there's any chance of porting it to an iterm2 theme? I have looked for conversion tools with no luck.

Currently researching how to make an iTerm theme, if I can get it together I'll make a PR, unless someone more experience can jump in.

**Comment by gabebw** [comment]
@tomspeak FWIW, I use this with the [Tomorrow Night Eighties](https://github.com/chriskempson/tomorrow-theme/tree/master/iTerm2) terminal theme, which has a few advantages:

1) Someone else already made it :)
2) It's '80s themed, just like 1989.vim
3) It's pastel-y and works well with the colors in this theme

Just my 2 cents!

**Comment by sonjapeterson** [comment]
Hi @tomspeak glad you like the theme! I have an iterm2 color scheme that I made to match it. Tomorrow Night Eighties is also a great choice as Gabe recommended!
[1989.itermcolors.zip](https://github.com/sonjapeterson/1989.vim/files/848078/1989.itermcolors.zip)

**Comment by tomspeak** [comment]
Works perfectly @sonjapeterson, appreciate it! You should add it to the repo and readme.
